name: Amazon Price Tracker

# Trigger workflow on push to main or on a schedule
on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 */3 * * *'  # every 3 hours

jobs:
  run-tracker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4

      - name: Run tracker
        env:
          ALERT_EMAIL: ${{ secrets.ALERT_EMAIL }}
          ALERT_PASSWORD: ${{ secrets.ALERT_PASSWORD }}
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: |
          python tracker.py

